pridėtas Hero image
front-end-by-rimantas/19-grupe-coming-soon pull request #31
Opened 2020-11-18 16:48 UTC by Vaidmine

pridėtas Hero image

2020-11-18 17:48 UTC, belauzas requested changes
Dar trūksta logotipo 👍

2020-11-18 18:47 UTC, Vaidmine commented
atsidariau folderį- logo ten buvo (dar nuo pirmos paskaitos ar pan) ;)
bet įdėjau dar vieną.

2020-11-18 18:48 UTC, Vaidmine commented
pridėtas logo

2020-11-19 11:39 UTC, Vaidmine commented
labas, nesuprantu, ar čia dar reikia kažką keisti, ar tiesiog nepadarytas "Merge" ir todėl man dega raudonai, kad "Changes requested"?

2020-11-19 12:34 UTC, belauzas approved these changes

2020-11-19 12:34 UTC, merged